version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_API_KEY: ${REACT_APP_API_KEY}
    ports:
      - '${PORT}:80'
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}
